# Generated by Django 6.0.5 on 2026-06-03 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_alter_budget_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
