# Generated by assistant to add missing `category` field required by tests
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0004_budget_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="category",
            field=models.CharField(
                max_length=20,
                choices=[
                    ("ENTERTAINMENT", "Entertainment"),
                    ("PRODUCTIVITY", "Productivity"),
                    ("UTILITIES", "Utilities"),
                    ("EDUCATION", "Education"),
                    ("SPORTS", "Sports"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
            ),
        ),
    ]
